### ISSUE TITLE
cutadapt output is inconsistent while running in singularity and conda

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/zarp#24]
@dominikburri discovered this issue while debugging today.

At the end of the workflow we get different output files for `cutadapt` depending which execution strategy we use, (on the test data) only because one column with version number is added to the output table. It is just a format issue, the actual result values are the same.

This is strange however since we specify the same version of `cutadapt` for both conda and singularity. Maybe they are pulling different patch versions? or different builds?

Anyway, should be easy to fix by freezing **exactly** the same version of the software for both apporaches.
This could potentially solve the problem we discovered in https://github.com/zavolanlab/zarp/pull/16#issuecomment-931562637 I think this might be the same thing manifested in a different place.

FYI @fgypas

**Comment by AngryMaciek** [comment]
I'll take a look into this one tomorrow...

**Comment by AngryMaciek** [comment]
@fgypas 

I wanted tu update the _cutadapt_ version so that maybe this issue is resolved.
I wanted to use this: https://anaconda.org/bioconda/cutadapt

I see this is under _bioconda_ but whenever I look at the biocontainers at the DockerHub the versions are much older: https://hub.docker.com/r/biocontainers/cutadapt/tags

Should we open an issue somewhere to request a container update?

**Comment by fgypas** [comment]
Yes, the containers are pushed to quay.io since some time.
See here: https://quay.io/repository/biocontainers/cutadapt?tab=tags

**Comment by AngryMaciek** [comment]
I have tested a new version of `cutadapt = 3.7`, both from Anaconda Cloud and official Singularity Container from _biocontainers_. The issue remains the same: the output table from the conda version contains one more column with a version specification, compared to the output table from container version. I get the impression that is by-design, since we had the same observation for version `3.4` See below:

Running in conda envs (`multiqc_cutadapt.txt`):
```
Sample	cutadapt_version	r_processed	r_with_adapters	r_too_short	r_written	bp_processed	bp_written	percent_trimmed	pairs_processed	r1_with_adapters	r2_with_adapters	pairs_too_short	pairs_written
synthetic_10_reads_mate_1_synthetic_10_reads_mate_1	3.7	10	0	0	10	750	750	0.0					
synthetic_10_reads_paired_synthetic_10_reads_paired.fq2	3.7					1500	1500	0.0	10	0	0	0	10
```
Running in singularity containers (`multiqc_cutadapt.txt`):
```
Sample	r_processed	r_with_adapters	r_too_short	r_written	bp_processed	bp_written	percent_trimmed	pairs_processed	r1_with_adapters	r2_with_adapters	pairs_too_short	pairs_written
synthetic_10_reads_mate_1_synthetic_10_reads_mate_1	10	0	0	10	750	750	0.0					
synthetic_10_reads_paired_synthetic_10_reads_paired.fq2					1500	1500	0.0	10	0	0	0	10
```

I think we should leave it be. It's good that we are aware of this difference but since this is the convention they stick by in the _biocontainers_ already I don't see much sense working around it...  

What do you think @fgypas and @uniqueg ?

**Comment by ninsch3000** [comment]
Will you update the md5sums for the conda run then?
(just ran into the issue, because ci fails on my branch with the conda integration test)

**Comment by uniqueg** [comment]
Kinda weird, this behavior. But fine by me to keep it @AngryMaciek

**Comment by AngryMaciek** [comment]
OK, I'm on it.

**Comment by mkatsanto** [comment]
Hey @AngryMaciek this is supposed to be one line in the environments. Is there some delay? Have you pushed the branch?

**Comment by AngryMaciek** [comment]
No, I did not push it yet, I am not sure I get correct `md5` now, testing locally.

**Comment by mkatsanto** [comment]
@AngryMaciek  You would not if the issue is fixed though right? Or do you get issues for different md5s?

**Comment by AngryMaciek** [comment]
@fgypas are you sure we have `1.10.1` in the containers? I have just pulled that exact one into a conda env and I get an internal MultiQC error:

```
[WARNING]         multiqc : MultiQC Version v1.12 now available!
Traceback (most recent call last):
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/bin/multiqc", line 6, in <module>
    from multiqc.__main__ import multiqc
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/multiqc/__main__.py", line 53, in <module>
    multiqc.run_cli(prog_name="multiqc")
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/multiqc/multiqc.py", line 225, in run_cli
    multiqc_run = run(
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/multiqc/multiqc.py", line 416, in run
    plugin_hooks.mqc_trigger("execution_start")
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/multiqc/utils/plugin_hooks.py", line 21, in mqc_trigger
    hook()
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/modules/hook.py", line 13, in execution_start
    config.update_dict(config.sp, {"ALFA": {"fn": "*ALFA_feature_counts.tsv"}})
  File "{CLASSIFIED}zarp/tests/test_integration_workflow_with_conda/.snakemake/conda/b8097abf081fd92a31cd0a07f530de2a/lib/python3.10/site-packages/multiqc/utils/config.py", line 256, in update_dict
    if isinstance(val, collections.Mapping):
AttributeError: module 'collections' has no attribute 'Mapping'
```

Maybe we should try the other way round? publish a new Zavolab-MultiQC-Plugins container with `1.12`?

**Comment by AngryMaciek** [comment]
@fgypas : What do you think?

**Comment by fgypas** [comment]
This is what I did:

`docker pull quay.io/biocontainers/zavolan-multiqc-plugins:1.3--pyh5e36f6f_0`

>1.3--pyh5e36f6f_0: Pulling from biocontainers/zavolan-multiqc-plugins
>c1a16a04cedd: Already exists
>4ca545ee6d5d: Already exists
>a6989faad520: Already exists
Digest: sha256:3383fc24f8ac5e3f310379c7f14b50bc63cac29954ae06672104f240c293d3d5
Status: Downloaded newer image for quay.io/biocontainers/zavolan-multiqc-plugins:1.3--pyh5e36f6f_0
quay.io/biocontainers/zavolan-multiqc-plugins:1.3--pyh5e36f6f_0

`docker images`

>REPOSITORY                                      TAG                 IMAGE ID       CREATED        SIZE
quay.io/biocontainers/zavolan-multiqc-plugins   1.3--pyh5e36f6f_0   61177ac47039   9 months ago   347MB

`docker run -it 61177ac47039 bash`
and then
`multiqc --version`
>multiqc, version 1.10.1

I will have a look again in the evening.

**Comment by fgypas** [comment]
So the issue was that it required additionally `python<3.10`. I opened #63 that fixes this.

**Comment by AngryMaciek** [comment]
Oh, I am sorry, I did not check that carefully.
